runtime: java
instance_class: F1
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5
